name: BitMaelum CI
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x, 1.15.x]
#        os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Go license
      run: |
        go get -u github.com/google/addlicense
        GOPATH=`go env GOPATH`
        shopt -s globstar
        $GOPATH/bin/addlicense -c "BitMaelum Authors" -l mit -y 2020 -check internal/**/*.go pkg/**/*.go tools/**/*.go cmd/**/*.go
    - name: Go imports
      run: |
        test -z "$(goimports -l .)"
    - name: Go vet
      run: |
        go vet ./...
    - name: Go static check
      run: |
        go get honnef.co/go/tools/cmd/staticcheck
        GOPATH=`go env GOPATH`
        $GOPATH/bin/staticcheck ./...
    - name: Go ineffassign
      run: |
        go get -u github.com/gordonklaus/ineffassign
        GOPATH=`go env GOPATH`
        $GOPATH/bin/ineffassign ./*
    - name: Go cyclo
      run: |
        go get -u github.com/fzipp/cmd/gocyclo
        GOPATH=`go env GOPATH`
        $GOPATH/bin/gocyclo -over 15 .
    - name: Go test
      run: |
        go test -race -coverprofile=coverage.txt -covermode=atomic ./...
    - name: Upload coverage report
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.txt
        flags: unittests
        name: codecov-umbrella
